/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as DashboardMonitorsRouteImport } from './routes/dashboard/monitors'
import { ServerRoute as ApiSlowEndpointServerRouteImport } from './routes/api/slow-endpoint'
import { ServerRoute as ApiInactiveMonitorsServerRouteImport } from './routes/api/inactive-monitors'
import { ServerRoute as ApiAllStatusPagesServerRouteImport } from './routes/api/all-status-pages'
import { ServerRoute as ApiAllMonitorsServerRouteImport } from './routes/api/all-monitors'

const rootServerRouteImport = createServerRootRoute()

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMonitorsRoute = DashboardMonitorsRouteImport.update({
  id: '/monitors',
  path: '/monitors',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSlowEndpointServerRoute = ApiSlowEndpointServerRouteImport.update({
  id: '/api/slow-endpoint',
  path: '/api/slow-endpoint',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiInactiveMonitorsServerRoute =
  ApiInactiveMonitorsServerRouteImport.update({
    id: '/api/inactive-monitors',
    path: '/api/inactive-monitors',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAllStatusPagesServerRoute = ApiAllStatusPagesServerRouteImport.update({
  id: '/api/all-status-pages',
  path: '/api/all-status-pages',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAllMonitorsServerRoute = ApiAllMonitorsServerRouteImport.update({
  id: '/api/all-monitors',
  path: '/api/all-monitors',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/monitors': typeof DashboardMonitorsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/monitors': typeof DashboardMonitorsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/monitors': typeof DashboardMonitorsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/dashboard/monitors' | '/dashboard/overview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/dashboard/monitors' | '/dashboard/overview'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/monitors'
    | '/dashboard/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/all-monitors': typeof ApiAllMonitorsServerRoute
  '/api/all-status-pages': typeof ApiAllStatusPagesServerRoute
  '/api/inactive-monitors': typeof ApiInactiveMonitorsServerRoute
  '/api/slow-endpoint': typeof ApiSlowEndpointServerRoute
}
export interface FileServerRoutesByTo {
  '/api/all-monitors': typeof ApiAllMonitorsServerRoute
  '/api/all-status-pages': typeof ApiAllStatusPagesServerRoute
  '/api/inactive-monitors': typeof ApiInactiveMonitorsServerRoute
  '/api/slow-endpoint': typeof ApiSlowEndpointServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/all-monitors': typeof ApiAllMonitorsServerRoute
  '/api/all-status-pages': typeof ApiAllStatusPagesServerRoute
  '/api/inactive-monitors': typeof ApiInactiveMonitorsServerRoute
  '/api/slow-endpoint': typeof ApiSlowEndpointServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/all-monitors'
    | '/api/all-status-pages'
    | '/api/inactive-monitors'
    | '/api/slow-endpoint'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/all-monitors'
    | '/api/all-status-pages'
    | '/api/inactive-monitors'
    | '/api/slow-endpoint'
  id:
    | '__root__'
    | '/api/all-monitors'
    | '/api/all-status-pages'
    | '/api/inactive-monitors'
    | '/api/slow-endpoint'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAllMonitorsServerRoute: typeof ApiAllMonitorsServerRoute
  ApiAllStatusPagesServerRoute: typeof ApiAllStatusPagesServerRoute
  ApiInactiveMonitorsServerRoute: typeof ApiInactiveMonitorsServerRoute
  ApiSlowEndpointServerRoute: typeof ApiSlowEndpointServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/monitors': {
      id: '/dashboard/monitors'
      path: '/monitors'
      fullPath: '/dashboard/monitors'
      preLoaderRoute: typeof DashboardMonitorsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/slow-endpoint': {
      id: '/api/slow-endpoint'
      path: '/api/slow-endpoint'
      fullPath: '/api/slow-endpoint'
      preLoaderRoute: typeof ApiSlowEndpointServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/inactive-monitors': {
      id: '/api/inactive-monitors'
      path: '/api/inactive-monitors'
      fullPath: '/api/inactive-monitors'
      preLoaderRoute: typeof ApiInactiveMonitorsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/all-status-pages': {
      id: '/api/all-status-pages'
      path: '/api/all-status-pages'
      fullPath: '/api/all-status-pages'
      preLoaderRoute: typeof ApiAllStatusPagesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/all-monitors': {
      id: '/api/all-monitors'
      path: '/api/all-monitors'
      fullPath: '/api/all-monitors'
      preLoaderRoute: typeof ApiAllMonitorsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardMonitorsRoute: typeof DashboardMonitorsRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardMonitorsRoute: DashboardMonitorsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAllMonitorsServerRoute: ApiAllMonitorsServerRoute,
  ApiAllStatusPagesServerRoute: ApiAllStatusPagesServerRoute,
  ApiInactiveMonitorsServerRoute: ApiInactiveMonitorsServerRoute,
  ApiSlowEndpointServerRoute: ApiSlowEndpointServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
